updated both workflows

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,13 +20,32 @@ jobs:
       - name: install ssh_key_pair
         run: ssh-keygen -t rsa -N "" -f "ec2_login_key" 
       - name: initialize&format
+        id: init
         run: |
           terraform init
           terraform fmt
+        continue-on-error: true
       - name: plan_apply
+        id: plan
         run: terraform plan -out myplan
+        continue-on-error: true
+      - name: retry_plan #(run on failure)
+        if: steps.plan.outcome == 'failure'
+        run: |
+          echo "retrying plan.."
+          terraform plan -out myplan || terraform plan -out myplan
       - name: apply_plan
+        id: apply
         run: terraform apply myplan
+        continue-on-error: true
+      - name: Post-Deployment Outputs
+        if: always()
+        run: terraform output
+      - name: Failure Notification
+        if: failure()
+        run: |
+          echo "Terraform provisioning Failed!"
+          exit 1
 
 
  
diff --git a/.github/workflows/destroy.yml b/.github/workflows/destroy.yml
--- a/.github/workflows/destroy.yml
+++ b/.github/workflows/destroy.yml
@@ -21,12 +21,31 @@ jobs:
         run: ssh-keygen -t rsa -N "" -f "ec2_login_key"
       - name: initialize
         run: terraform init
+        continue-on-error: true
+
       - name: plan_destroy
         id: plan
         run: terraform plan -destroy -out myplan
         continue-on-error: true
+
+      - name: retry_plan #(on failure)
+        if: steps.plan.outcome == 'failure'
+        run: |
+          echo "plan failed, retrying.."
+          terraform plan -destroy -out myplan || terraform plan -destroy -out myplan
+        continue-on-error: true
+
       - name: apply_destroy
         run: terraform apply myplan
         continue-on-error: true
+      - name: Post-Deployment Outputs
+        if: always()
+        run: terraform output
+      - name: Failure Notification
+        if: failure()
+        run: |
+          echo "Terraform destroy Failed!"
+          exit 1
+
           
     
